cF1: cF1{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F1>
    , <&macro_release &kp LCTRL>
    ;
};

cF2: cF2{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F2>
    , <&macro_release &kp LCTRL>
    ;
};

cF3: cF3{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F3>
    , <&macro_release &kp LCTRL>
    ;
};

cF4: cF4{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F4>
    , <&macro_release &kp LCTRL>
    ;
};

cF5: cF5{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F5>
    , <&macro_release &kp LCTRL>
    ;
};

cF6: cF6{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F6>
    , <&macro_release &kp LCTRL>
    ;
};

cF7: cF7{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F7>
    , <&macro_release &kp LCTRL>
    ;
};

cF8: cF8{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F8>
    , <&macro_release &kp LCTRL>
    ;
};

cF9: cF9{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F9>
    , <&macro_release &kp LCTRL>
    ;
};

cF10: cF10{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F10>
    , <&macro_release &kp LCTRL>
    ;
};

cF11: cF11{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F11>
    , <&macro_release &kp LCTRL>
    ;
};

cF12: cF12{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F12>
    , <&macro_release &kp LCTRL>
    ;
};

zed_em_kay: zed_em_kay {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LSHFT>
    , <&macro_tap &kp Z &kp M &kp K>
    , <&macro_release &kp LSHFT>
    ;
};

sukusho: sukusho {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F10>
    , <&macro_release &kp LCTRL>
    ;
};

the: the {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp T &kp H &kp E>
    ;
};

parens_: parens_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp LPAR &kp RPAR &kp LEFT>
    ;
};

brace_: brace_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp LBRC &kp RBRC &kp LEFT>
    ;
};

bracket_: bracket_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp LBKT &kp RBKT &kp LEFT>
    ;
};

bracket2_: bracket2_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 100>
    , <&macro_tap &kp LBKT &kp RBKT &kp LEFT &kp ENTER &kp UP>
    ;
};

/* starr_: starr_ { */
/* #binding-cells = <0>; */
/* bindings */
/* = <&macro_tap_time 1> */
/* , <&macro_tap &kp STAR &kp STAR &kp LEFT UP> */
/* ; */
/* }; */

quote_: quote_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp DQT &kp DQT &kp LEFT>
    ;
};

squote_: squote_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp SQT &kp SQT &kp LEFT>
    ;
};

assign_: assign_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp COLON &kp EQUAL &kp SPC>
    ;
};

uneq: uneq {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp EXCL &kp EQUAL &kp SPC>
    ;
};

https: https {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp H &kp T &kp T &kp P  &kp S &kp COLON &kp FSLH &kp FSLH>
    ;
};

qj: qj {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp Q &kp J>
    , <&macro_release &kp LCTRL>
    ;
};

you: you {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp Y &kp O &kp U>
    ;
};

ing: ing {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp I &kp N &kp G>
    ;
};

and_: and_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp A &kp N &kp D>
    ;
};

hat_: hat_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp H &kp A &kp T>
    ;
};

thi: thi {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp T &kp H &kp I>
    ;
};

th_: th_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp T &kp H>
    ;
};

in_: in_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp I &kp N>
    ;
};

be_: be_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp B &kp E>
    ;
};

ver: ver {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp V &kp E &kp R>
    ;
};

home: home {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp TILDE &kp FSLH>
    ;
};

questionm: questionm {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp TILDE &kp FSLH>
    ;
};

hin: hin {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp H &kp I &kp N>
    ;
};

eve: eve {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp E &kp V &kp E>
    ;
};

for_: for_ {
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_tap &kp F &kp O &kp R>
    ;
};

cuter: cuter{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp X>
    , <&macro_release &kp LCTRL>
    ;
};

aller: aller{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp A &kp C>
    , <&macro_release &kp LCTRL>
    ;
};

deler: deler{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp BSPC>
    , <&macro_release &kp LCTRL>
    ;
};

allcuter: allcuter{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp A &kp X>
    , <&macro_release &kp LCTRL>
    ;
};

paster2: paster2{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp V>
    , <&macro_release &kp LCTRL>
    , <&macro_tap &kp ENTER>
    ;
};

paster: paster{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp V>
    , <&macro_release &kp LCTRL>
    ;
};

copyer: copyer{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp C>
    , <&macro_release &kp LCTRL>
    ;
};

allcopyer: allcopyer{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp A &kp C>
    , <&macro_release &kp LCTRL>
    ;
};

cutter: cutter{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp X>
    , <&macro_release &kp LCTRL>
    ;
};

searcher: searcher{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp F>
    , <&macro_release &kp LCTRL>
    ;
};

closer: closer{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp W>
    , <&macro_release &kp LCTRL>
    ;
};

lefter: lefter{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp PG_UP>
    , <&macro_release &kp LCTRL>
    ;
};

righter: righter{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL>
    , <&macro_tap &kp PG_DN>
    , <&macro_release &kp LCTRL>
    ;
};

/*  C-S-t */
restorer: restorer{
  compatible = "zmk,behavior-macro";
#binding-cells = <0>;
  bindings
    = <&macro_tap_time 1>
    , <&macro_press &kp LCTRL &kp LSHFT>
    , <&macro_tap &kp T>
    , <&macro_release &kp LCTRL &kp LSHFT>
    ;
};
